import type { Language } from '../types';

export const LANGUAGES: Language[] = [
  {
    code: 'ja-JP',
    name: '일본어',
    expressions: [
      { foreign: "こんにちは", pronunciation: "Konnichiwa", korean: "안녕하세요", level: '초급' },
      { foreign: "すみません", pronunciation: "Sumimasen", korean: "실례합니다 / 미안합니다", level: '초급' },
      { foreign: "ありがとう", pronunciation: "Arigatou", korean: "고맙습니다", level: '초급' },
      { foreign: "これはいくらですか？", pronunciation: "Kore wa ikura desu ka?", korean: "이것은 얼마인가요?", level: '초급' },
      { foreign: "お願いします", pronunciation: "Onegaishimasu", korean: "부탁합니다", level: '초급' },
      { foreign: "はい", pronunciation: "Hai", korean: "네", level: '초급' },
      { foreign: "いいえ", pronunciation: "Iie", korean: "아니요", level: '초급' },
      { foreign: "わかりません", pronunciation: "Wakarimasen", korean: "모르겠습니다", level: '초급' },
      { foreign: "駅はどこですか？", pronunciation: "Eki wa doko desu ka?", korean: "역은 어디인가요?", level: '초급' },
      { foreign: "トイレはどこですか？", pronunciation: "Toire wa doko desu ka?", korean: "화장실은 어디인가요?", level: '초급' },
      { foreign: "これをください", pronunciation: "Kore o kudasai", korean: "이것을 주세요", level: '초급' },
      { foreign: "おいしいです", pronunciation: "Oishii desu", korean: "맛있습니다", level: '초급' },
      { foreign: "お勘定お願いします", pronunciation: "Okanjou onegaishimasu", korean: "계산서 부탁합니다", level: '중급' },
      { foreign: "助けてください", pronunciation: "Tasukete kudasai", korean: "도와주세요", level: '중급' },
      { foreign: "もう一度お願いします", pronunciation: "Mou ichido onegaishimasu", korean: "다시 한번 부탁합니다", level: '중급' },
      { foreign: "写真を撮ってもいいですか？", pronunciation: "Shashin o totte mo ii desu ka?", korean: "사진을 찍어도 될까요?", level: '중급' },
      { foreign: "おすすめは何ですか？", pronunciation: "Osusume wa nan desu ka?", korean: "추천 메뉴는 무엇인가요?", level: '중급' },
      { foreign: "チェックインお願いします", pronunciation: "Chekkuin onegaishimasu", korean: "체크인 부탁합니다", level: '중급' },
      { foreign: "Wi-Fiはありますか？", pronunciation: "Wi-Fi wa arimasu ka?", korean: "와이파이 있나요?", level: '초급' },
      { foreign: "さようなら", pronunciation: "Sayounara", korean: "안녕히 가세요", level: '초급' },
      { foreign: "おはようございます", pronunciation: "Ohayou gozaimasu", korean: "좋은 아침입니다", level: '초급' },
      { foreign: "こんばんは", pronunciation: "Konbanwa", korean: "안녕하세요 (저녁 인사)", level: '초급' },
      { foreign: "ごめんなさい", pronunciation: "Gomen nasai", korean: "죄송합니다", level: '초급' },
      { foreign: "メニューをください", pronunciation: "Menyuu o kudasai", korean: "메뉴판을 주세요", level: '중급' },
      { foreign: "禁煙席をお願いします", pronunciation: "Kin'en seki o onegaishimasu", korean: "금연석으로 부탁합니다", level: '고급' },
      { foreign: "予約をしました", pronunciation: "Yoyaku o shimashita", korean: "예약했습니다", level: '고급' },
    ]
  },
  {
    code: 'en-US',
    name: '영어',
    expressions: [
      { foreign: "Hello", pronunciation: "Hello", korean: "안녕하세요", level: '초급' },
      { foreign: "Excuse me", pronunciation: "Excuse me", korean: "실례합니다", level: '초급' },
      { foreign: "Thank you", pronunciation: "Thank you", korean: "고맙습니다", level: '초급' },
      { foreign: "How much is this?", pronunciation: "How much is this?", korean: "이것은 얼마인가요?", level: '초급' },
      { foreign: "Please", pronunciation: "Please", korean: "부탁합니다", level: '초급' },
      { foreign: "Yes", pronunciation: "Yes", korean: "네", level: '초급' },
      { foreign: "No", pronunciation: "No", korean: "아니요", level: '초급' },
      { foreign: "I don't understand", pronunciation: "I don't understand", korean: "이해하지 못했습니다", level: '초급' },
      { foreign: "Where is the station?", pronunciation: "Where is the station?", korean: "역은 어디인가요?", level: '초급' },
      { foreign: "Where is the restroom?", pronunciation: "Where is the restroom?", korean: "화장실은 어디인가요?", level: '초급' },
      { foreign: "I'll take this one", pronunciation: "I'll take this one", korean: "이것으로 할게요", level: '중급' },
      { foreign: "It's delicious", pronunciation: "It's delicious", korean: "맛있습니다", level: '초급' },
      { foreign: "Check, please", pronunciation: "Check, please", korean: "계산서 부탁합니다", level: '중급' },
      { foreign: "Help me, please", pronunciation: "Help me, please", korean: "도와주세요", level: '중급' },
      { foreign: "Could you repeat that?", pronunciation: "Could you repeat that?", korean: "다시 한번 말씀해주시겠어요?", level: '고급' },
      { foreign: "Can I take a picture?", pronunciation: "Can I take a picture?", korean: "사진을 찍어도 될까요?", level: '중급' },
      { foreign: "What do you recommend?", pronunciation: "What do you recommend?", korean: "추천 메뉴는 무엇인가요?", level: '중급' },
      { foreign: "I'd like to check in", pronunciation: "I'd like to check in", korean: "체크인하고 싶습니다", level: '고급' },
      { foreign: "Do you have Wi-Fi?", pronunciation: "Do you have Wi-Fi?", korean: "와이파이 있나요?", level: '초급' },
      { foreign: "Goodbye", pronunciation: "Goodbye", korean: "안녕히 가세요", level: '초급' },
    ]
  },
  {
    code: 'zh-CN',
    name: '중국어',
    expressions: [
      { foreign: "你好", pronunciation: "Nǐ hǎo", korean: "안녕하세요", level: '초급' },
      { foreign: "谢谢", pronunciation: "Xièxiè", korean: "고맙습니다", level: '초급' },
      { foreign: "不客气", pronunciation: "Bú kèqì", korean: "천만에요", level: '초급' },
      { foreign: "对不起", pronunciation: "Duìbuqǐ", korean: "미안합니다", level: '초급' },
      { foreign: "这个多少钱？", pronunciation: "Zhège duōshǎo qián?", korean: "이것은 얼마인가요?", level: '초급' },
      { foreign: "洗手间在哪儿？", pronunciation: "Xǐshǒujiān zài nǎ'er?", korean: "화장실은 어디인가요?", level: '초급' },
      { foreign: "我听不懂", pronunciation: "Wǒ tīng bù dǒng", korean: "알아듣지 못하겠습니다", level: '중급' },
      { foreign: "请帮我一下", pronunciation: "Qǐng bāng wǒ yīxià", korean: "좀 도와주세요", level: '중급' },
      { foreign: "买单", pronunciation: "Mǎidān", korean: "계산할게요", level: '중급' },
      { foreign: "太贵了", pronunciation: "Tài guìle", korean: "너무 비싸요", level: '중급' },
      { foreign: "便宜一点可以吗？", pronunciation: "Piányí yīdiǎn kěyǐ ma?", korean: "좀 깎아주실 수 있나요?", level: '고급' },
      { foreign: "我要这个", pronunciation: "Wǒ yào zhège", korean: "이걸로 주세요", level: '초급' },
      { foreign: "很好吃", pronunciation: "Hěn hǎo chī", korean: "아주 맛있습니다", level: '초급' },
      { foreign: "菜单", pronunciation: "Càidān", korean: "메뉴판을 주세요", level: '중급' },
      { foreign: "再见", pronunciation: "Zàijiàn", korean: "안녕히 가세요", level: '초급' },
      { foreign: "救命！", pronunciation: "Jiùmìng!", korean: "살려주세요!", level: '고급' },
      { foreign: "机场在哪儿？", pronunciation: "Jīchǎng zài nǎ'er?", korean: "공항은 어디인가요?", level: '중급' },
      { foreign: "我迷路了", pronunciation: "Wǒ mílùle", korean: "길을 잃었어요", level: '고급' },
      { foreign: "有空房吗？", pronunciation: "Yǒu kòngfáng ma?", korean: "빈 방 있나요?", level: '고급' },
      { foreign: "我预订了", pronunciation: "Wǒ yùdìng le", korean: "예약했습니다", level: '고급' },
    ]
  }
];
